version: '3.1'

services:

  reverse-proxy:
    image: reverse-proxy
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
    depends_on:
      - feature-toggler-postgres
      - feature-toggler-client
      - feature-toggler-server
    ports:
      - 80:80
    restart: always
  
  feature-toggler-client:
    image: feature-toggler-client
    container_name: feature-toggler-client
    build:
      context: ./feature-toggler-frontend
    volumes:
      - ./feature-toggler-client/dist:/usr/src/app/www
    ports:
      - 8080:80
    restart: on-failure

  feature-toggler-postgres:
    container_name: feature-toggler-postgres
    image: postgres
    restart: unless-stopped
    environment:
    - POSTGRES_USER=change-this-user
    - POSTGRES_PASSWORD=change-this-password
    - POSTGRES_DB=feature-toggler
    ports:
    - "7654:5432"
    volumes:
    - psql:/var/lib/postgresql/data
  
  feature-toggler-backend:
    image: feature-toggler-backend
    container_name: feature-toggler-backend
    build:
      context: ./feature-toggler-backend
    env_file:
        - ./feature-toggler-backend/.env
    ports:
      - 3014:3000
    restart: on-failure
  