version: '3.1'

services:

  reverse-proxy:
    image: reverse-proxy
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
    depends_on:
      - feature-toggler-postgres
      - feature-toggler-dashboard
      - feature-toggler-server
    ports:
      - 80:80
    restart: always
  
  feature-toggler-dashboard:
    image: feature-toggler-dashboard
    container_name: feature-toggler-dashboard
    environment:
      - REACT_APP_BASE_URL=http://localhost:3010/api
    build:
      context: ./feature-toggler-dashboard
    volumes:
      - ./feature-toggler-dashboard/build:/usr/src/app/www
    ports:
      - 8080:80
    restart: on-failure

  feature-toggler-postgres:
    container_name: feature-toggler-postgres
    image: postgres
    restart: unless-stopped
    environment:
    - POSTGRES_USER=ft
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=feature-toggler
    ports:
    - 7654:5432
    volumes:
    - ./DB:/var/lib/postgresql/data
    - ./DBINIT/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  feature-toggler-server:
    image: feature-toggler-server
    container_name: feature-toggler-server
    build:
      context: ./feature-toggler-server
    environment:
        - SERVER_PORT=3010
        - DB_TYPE=SQLITE
        - DB_NAME=feature-toggler
        - DB_USERNAME=ft
        - DB_PASSWORD=password
        - DB_PORT=7654
        - DB_HOST=localhost
    ports:
      - 3010:3010
    restart: on-failure
  